
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.EventBox eventbox1;

	private global::Gtk.Frame frame3;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.VBox vbox1;

	private global::Gtk.Frame frame6;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textview1;

	private global::Gtk.Label GtkLabel1;

	private global::Gtk.Table table3;

	private global::Gtk.Button button11;

	private global::Gtk.Button button13;

	private global::Gtk.Button button15;

	private global::Gtk.Button button17;

	private global::Gtk.Button button19;

	private global::Gtk.Button button4;

	private global::Gtk.Button button6;

	private global::Gtk.Button button9;

	private global::Gtk.EventBox eventbox5;

	private global::Gtk.Button button8;

	private global::Gtk.Table table5;

	private global::Gtk.Button button21;

	private global::Gtk.Button button23;

	private global::Gtk.Button button25;

	private global::Gtk.Button button27;

	private global::Gtk.Button button29;

	private global::Gtk.Button button31;

	private global::Gtk.Button button33;

	private global::Gtk.Button button35;

	private global::Gtk.Button button37;

	private global::Gtk.Label GtkLabel2;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.eventbox1 = new global::Gtk.EventBox();
		this.eventbox1.Name = "eventbox1";
		// Container child eventbox1.Gtk.Container+ContainerChild
		this.frame3 = new global::Gtk.Frame();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame6 = new global::Gtk.Frame();
		this.frame6.Name = "frame6";
		this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame6.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.GtkScrolledWindow.Add(this.textview1);
		this.GtkAlignment1.Add(this.GtkScrolledWindow);
		this.frame6.Add(this.GtkAlignment1);
		this.GtkLabel1 = new global::Gtk.Label();
		this.GtkLabel1.Name = "GtkLabel1";
		this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString("<b>GtkFrame</b>");
		this.GtkLabel1.UseMarkup = true;
		this.frame6.LabelWidget = this.GtkLabel1;
		this.vbox1.Add(this.frame6);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame6]));
		w4.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table3 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.button11 = new global::Gtk.Button();
		this.button11.CanFocus = true;
		this.button11.Name = "button11";
		this.button11.UseUnderline = true;
		this.button11.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table3.Add(this.button11);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3[this.button11]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button13 = new global::Gtk.Button();
		this.button13.CanFocus = true;
		this.button13.Name = "button13";
		this.button13.UseUnderline = true;
		this.button13.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table3.Add(this.button13);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3[this.button13]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.LeftAttach = ((uint)(2));
		w6.RightAttach = ((uint)(3));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button15 = new global::Gtk.Button();
		this.button15.CanFocus = true;
		this.button15.Name = "button15";
		this.button15.UseUnderline = true;
		this.button15.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table3.Add(this.button15);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3[this.button15]));
		w7.TopAttach = ((uint)(2));
		w7.BottomAttach = ((uint)(3));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button17 = new global::Gtk.Button();
		this.button17.CanFocus = true;
		this.button17.Name = "button17";
		this.button17.UseUnderline = true;
		this.button17.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table3.Add(this.button17);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3[this.button17]));
		w8.TopAttach = ((uint)(2));
		w8.BottomAttach = ((uint)(3));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button19 = new global::Gtk.Button();
		this.button19.CanFocus = true;
		this.button19.Name = "button19";
		this.button19.UseUnderline = true;
		this.button19.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table3.Add(this.button19);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3[this.button19]));
		w9.TopAttach = ((uint)(2));
		w9.BottomAttach = ((uint)(3));
		w9.LeftAttach = ((uint)(2));
		w9.RightAttach = ((uint)(3));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table3.Add(this.button4);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3[this.button4]));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table3.Add(this.button6);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table3[this.button6]));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button9 = new global::Gtk.Button();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table3.Add(this.button9);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3[this.button9]));
		w12.TopAttach = ((uint)(1));
		w12.BottomAttach = ((uint)(2));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.eventbox5 = new global::Gtk.EventBox();
		this.eventbox5.Name = "eventbox5";
		// Container child eventbox5.Gtk.Container+ContainerChild
		this.button8 = new global::Gtk.Button();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.eventbox5.Add(this.button8);
		this.table3.Add(this.eventbox5);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3[this.eventbox5]));
		w14.LeftAttach = ((uint)(2));
		w14.RightAttach = ((uint)(3));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add(this.table3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table3]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table5 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
		this.table5.Name = "table5";
		this.table5.RowSpacing = ((uint)(6));
		this.table5.ColumnSpacing = ((uint)(6));
		// Container child table5.Gtk.Table+TableChild
		this.button21 = new global::Gtk.Button();
		this.button21.CanFocus = true;
		this.button21.Name = "button21";
		this.button21.UseUnderline = true;
		this.button21.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table5.Add(this.button21);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table5[this.button21]));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.button23 = new global::Gtk.Button();
		this.button23.CanFocus = true;
		this.button23.Name = "button23";
		this.button23.UseUnderline = true;
		this.button23.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table5.Add(this.button23);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table5[this.button23]));
		w17.LeftAttach = ((uint)(1));
		w17.RightAttach = ((uint)(2));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.button25 = new global::Gtk.Button();
		this.button25.CanFocus = true;
		this.button25.Name = "button25";
		this.button25.UseUnderline = true;
		this.button25.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table5.Add(this.button25);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table5[this.button25]));
		w18.LeftAttach = ((uint)(2));
		w18.RightAttach = ((uint)(3));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.button27 = new global::Gtk.Button();
		this.button27.CanFocus = true;
		this.button27.Name = "button27";
		this.button27.UseUnderline = true;
		this.button27.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table5.Add(this.button27);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table5[this.button27]));
		w19.TopAttach = ((uint)(1));
		w19.BottomAttach = ((uint)(2));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.button29 = new global::Gtk.Button();
		this.button29.CanFocus = true;
		this.button29.Name = "button29";
		this.button29.UseUnderline = true;
		this.button29.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table5.Add(this.button29);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table5[this.button29]));
		w20.TopAttach = ((uint)(1));
		w20.BottomAttach = ((uint)(2));
		w20.LeftAttach = ((uint)(1));
		w20.RightAttach = ((uint)(2));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.button31 = new global::Gtk.Button();
		this.button31.CanFocus = true;
		this.button31.Name = "button31";
		this.button31.UseUnderline = true;
		this.button31.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table5.Add(this.button31);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table5[this.button31]));
		w21.TopAttach = ((uint)(1));
		w21.BottomAttach = ((uint)(2));
		w21.LeftAttach = ((uint)(2));
		w21.RightAttach = ((uint)(3));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.button33 = new global::Gtk.Button();
		this.button33.CanFocus = true;
		this.button33.Name = "button33";
		this.button33.UseUnderline = true;
		this.button33.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table5.Add(this.button33);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table5[this.button33]));
		w22.TopAttach = ((uint)(2));
		w22.BottomAttach = ((uint)(3));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.button35 = new global::Gtk.Button();
		this.button35.CanFocus = true;
		this.button35.Name = "button35";
		this.button35.UseUnderline = true;
		this.button35.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table5.Add(this.button35);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table5[this.button35]));
		w23.TopAttach = ((uint)(2));
		w23.BottomAttach = ((uint)(3));
		w23.LeftAttach = ((uint)(1));
		w23.RightAttach = ((uint)(2));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.button37 = new global::Gtk.Button();
		this.button37.CanFocus = true;
		this.button37.Name = "button37";
		this.button37.UseUnderline = true;
		this.button37.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table5.Add(this.button37);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table5[this.button37]));
		w24.TopAttach = ((uint)(2));
		w24.BottomAttach = ((uint)(3));
		w24.LeftAttach = ((uint)(2));
		w24.RightAttach = ((uint)(3));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add(this.table5);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table5]));
		w25.Position = 2;
		w25.Expand = false;
		w25.Fill = false;
		this.GtkAlignment.Add(this.vbox1);
		this.frame3.Add(this.GtkAlignment);
		this.GtkLabel2 = new global::Gtk.Label();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>GtkFrame</b>");
		this.GtkLabel2.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel2;
		this.eventbox1.Add(this.frame3);
		this.Add(this.eventbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 413;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
